### ISSUE TITLE
Problems with implementation in Docker

### ISSUE THREAD

**Issue by VZMDeadAngel** [olegtarasov/FastText.NetWrapper#29] opened 2021-11-10 21:44 UTC
Hi.
I created a simple Net core 5.0 application.
```using FastText.NetWrapper;
namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var fasttext = new FastTextWrapper();
        }
    }
}
```
Created Dockerfile. (Such a file is created by default Visual Studio)
```
FROM mcr.microsoft.com/dotnet/runtime:5.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["ConsoleApp/ConsoleApp.csproj", "ConsoleApp/"]
RUN dotnet restore "ConsoleApp/ConsoleApp.csproj"
COPY . .
WORKDIR "/src/ConsoleApp"
RUN dotnet build "ConsoleApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ConsoleApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ConsoleApp.dll"]
```
As a result, I see an error.

**Unable to load shared library 'fasttext' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libfasttext: cannot open shared object file: No such file or directory**

I'm using Docker Desktop for Windows with Linux enviropment.

What am I doing wrong? Thank you!

**Comment by olegtarasov** [comment] 2021-11-17 05:35
Hi @VZMDeadAngel! Thank you for reporting this issue. I will try to reproduce and fix it in a couple of days.

**Comment by olegtarasov** [comment] 2021-11-19 07:22
@VZMDeadAngel I've just pushed version `1.2.6-pre`. Can you please try it out? I ditched the whole process of unpacking native libraries from resources, and they are now just bundled with target project.

**Comment by VZMDeadAngel** [comment] 2021-11-19 08:24
There are no packages in NuGet.
```
Unable to find package FastText.Native.Linux with version (>= 1.10.111-pre)
Unable to find package FastText.Native.MacOs with version (>= 1.10.111-pre)
Unable to find package FastText.Native.Windows with version (>= 1.10.113-pre)
```

**Comment by olegtarasov** [comment] 2021-11-19 17:57
@VZMDeadAngel Sorry about that, forgot to put in the correct dependencies. Please try v. `1.2.30-pre`.

**Comment by olegtarasov** [comment] 2021-11-20 13:13
I verified the new approach with your Docker config and it seems to be working. I'm releasing v. `1.3.0` and closing this issue. Please feel free to reopen it, should you discover things not working correctly.

**Closed by olegtarasov** 2021-11-20 13:13 UTC

**Comment by VZMDeadAngel** [comment] 2021-11-22 10:37
@olegtarasov 
The problem is solved. Thanks!

**Comment by gianlucaschoefer** [comment] 2025-04-07 14:29
@olegtarasov is it possible to reopen this issue? I have the same problems with v1.3.1 on Docker for Desktop on MacOS.

Other things I tried:
- Use .NET 8 or .NET 9
- Downgrade to v1.30.0
- manually copy the share objects to the docker container (even though I confirmed that `libfasttext.so` is available)

Let me know if I can help you with identifying the issue.

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'fasttext' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
2025-04-07T14:29:13.655627382Z /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.14/fasttext.so: cannot open shared object file: No such file or directory
2025-04-07T14:29:13.655628799Z /app/bin/Debug/net8.0/fasttext.so: cannot open shared object file: No such file or directory
2025-04-07T14:29:13.655630174Z /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.14/libfasttext.so: cannot open shared object file: No such file or directory
2025-04-07T14:29:13.655631215Z /app/bin/Debug/net8.0/libfasttext.so: cannot open shared object file: No such file or directory
2025-04-07T14:29:13.655632382Z /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.14/fasttext: cannot open shared object file: No such file or directory
2025-04-07T14:29:13.655633382Z /app/bin/Debug/net8.0/fasttext: cannot open shared object file: No such file or directory
2025-04-07T14:29:13.655634299Z /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.14/libfasttext: cannot open shared object file: No such file or directory
2025-04-07T14:29:13.655635299Z /app/bin/Debug/net8.0/libfasttext: cannot open shared object file: No such file or directory
2025-04-07T14:29:13.655636174Z 
```
